# Generated by Django 5.2.7 on 2025-10-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saree',
            name='image',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
